"""SQLAlchemy Core tables mirroring alembic/versions/0001_core_schema.py.

Constraints, defaults, grants and policies live in the migration; these objects only build
queries. tests/integration/test_db_schema.py checks that names and nullability match.
"""

from typing import Any

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY, JSONB

metadata = sa.MetaData()

# Tables with row-level security (users plus every table with a user_id column).
USER_TABLES: tuple[str, ...] = (
    "users",
    "profiles",
    "plans",
    "plan_items",
    "sessions",
    "session_metrics",
    "session_errors",
    "glossary_items",
    "review_states",
    "review_logs",
    "audit_log",
    "web_sessions",
)
# Seed tables: no RLS, read only for tutor_app.
TRACK_TABLES: tuple[str, ...] = ("track_items", "track_chunks")

TS = sa.DateTime(timezone=True)
TEXT_ARRAY = ARRAY(sa.Text)


def _req(name: str, type_: Any) -> sa.Column[Any]:
    return sa.Column(name, type_, nullable=False)


def _opt(name: str, type_: Any) -> sa.Column[Any]:
    return sa.Column(name, type_, nullable=True)


def _uuid_pk() -> sa.Column[Any]:
    """UUID primary key generated by the database (gen_random_uuid() in the migration)."""
    return sa.Column("id", sa.Uuid, primary_key=True, server_default=sa.text("gen_random_uuid()"))


users = sa.Table(
    "users",
    metadata,
    _uuid_pk(),
    _req("google_sub", sa.Text),
    _opt("email", sa.Text),
    _req("display_name", sa.Text),
    _req("native_lang", sa.Text),
    _req("role", sa.Text),
    _req("lang", sa.Text),
    _req("timezone", sa.Text),
    _req("reduce_motion", sa.Boolean),
    _opt("install_prompt_dismissed_at", TS),
    _opt("last_celebrated_session_id", sa.Uuid),
    _opt("deletion_requested_at", TS),
    _req("email_weekly", sa.Boolean),
    _req("email_reminders", sa.Boolean),
    _opt("mcp_first_seen_at", TS),
    _req("created_at", TS),
    _opt("deleted_at", TS),
)

profiles = sa.Table(
    "profiles",
    metadata,
    sa.Column("user_id", sa.Uuid, primary_key=True),
    _req("domains", TEXT_ARRAY),
    _req("use_cases", TEXT_ARRAY),
    _opt("goal_text", sa.Text),
    _req("minutes_per_day", sa.SmallInteger),
    _req("days_per_week", sa.SmallInteger),
    _req("self_level", sa.Text),
    _req("target_level", sa.Text),
    _opt("target_date", sa.Date),
    _req("onboarded_at", TS),
    _req("updated_at", TS),
)

track_items = sa.Table(
    "track_items",
    metadata,
    sa.Column("id", sa.Text, primary_key=True),
    _req("domain", sa.Text),
    _req("order_no", sa.Integer),
    _req("cefr", sa.Text),
    _req("can_do_en", sa.Text),
    _req("can_do_es", sa.Text),
    _req("skill", sa.Text),
    _req("interaction_type", sa.Text),
    _req("use_cases", TEXT_ARRAY),
    _req("character", sa.Text),
    _req("objective", sa.Text),
    _req("obstacle", sa.Text),
    _req("scenario_hint", sa.Text),
)

track_chunks = sa.Table(
    "track_chunks",
    metadata,
    sa.Column("id", sa.Text, primary_key=True),
    _req("track_item_id", sa.Text),
    _req("position", sa.SmallInteger),
    _req("text", sa.Text),
    _req("example", sa.Text),
)

plans = sa.Table(
    "plans",
    metadata,
    _uuid_pk(),
    _req("user_id", sa.Uuid),
    _req("version", sa.Integer),
    _req("status", sa.Text),
    _req("generated_at", TS),
    _req("rationale", JSONB),
)

plan_items = sa.Table(
    "plan_items",
    metadata,
    _uuid_pk(),
    _req("plan_id", sa.Uuid),
    _req("user_id", sa.Uuid),
    _req("week_no", sa.Integer),
    _req("order_no", sa.Integer),
    _req("track_item_id", sa.Text),
    _req("variant", sa.Text),
    _req("status", sa.Text),
    _opt("done_session_id", sa.Uuid),
)

sessions = sa.Table(
    "sessions",
    metadata,
    _uuid_pk(),
    _req("user_id", sa.Uuid),
    _opt("plan_item_id", sa.Uuid),
    _req("track_item_id", sa.Text),
    _opt("prep_text", sa.Text),
    _req("mode", sa.Text),
    _req("client", sa.Text),
    _req("started_at", TS),
    _opt("ended_at", TS),
    _req("status", sa.Text),
    _req("low_trust", sa.Boolean),
    _req("brief_variant", sa.Text),
    _req("chunks_offered", TEXT_ARRAY),
    _opt("task_result", sa.Text),
    _opt("hints_given", sa.Integer),
    _opt("cefr_estimate_speaking", sa.Text),
    _opt("cefr_confidence", sa.Text),
    _req("cefr_excluded", sa.Boolean),
    _opt("confidence_1_5", sa.SmallInteger),
    _opt("raw_evidence", JSONB),
    _opt("result", JSONB),
)

session_metrics = sa.Table(
    "session_metrics",
    metadata,
    sa.Column("session_id", sa.Uuid, primary_key=True),
    _req("user_id", sa.Uuid),
    _req("user_words", sa.Integer),
    _opt("assistant_words_estimate", sa.Integer),
    _opt("user_ratio", sa.Double),
    _req("turns", sa.Integer),
    _req("words_per_turn", sa.Double),
    _req("duration_min", sa.Double),
    _req("user_words_per_min", sa.Double),
    _req("errors_total", sa.Integer),
    _req("errors_rejected", sa.Integer),
    _req("errors_by_category", JSONB),
    _req("errors_per_100w", sa.Double),
    _req("recurring_errors", sa.Integer),
    _req("uptake_count", sa.Integer),
    _req("chunks_offered", sa.Integer),
    _req("chunks_used", sa.Integer),
    _req("chunks_rejected", sa.Integer),
    _req("activation_rate", sa.Double),
    _opt("unique_lemmas", sa.Integer),
    _opt("lexical_diversity", sa.Double),
    _opt("l1_switches", sa.Integer),
)

session_errors = sa.Table(
    "session_errors",
    metadata,
    _uuid_pk(),
    _req("session_id", sa.Uuid),
    _req("user_id", sa.Uuid),
    _req("said", sa.Text),
    _req("correct", sa.Text),
    _req("correct_norm", sa.Text),
    _req("category", sa.Text),
    _req("turn_index", sa.Integer),
)

glossary_items = sa.Table(
    "glossary_items",
    metadata,
    _uuid_pk(),
    _req("user_id", sa.Uuid),
    _req("kind", sa.Text),
    _req("text", sa.Text),
    _req("text_norm", sa.Text),
    _req("meaning", sa.Text),
    _req("context_sentence", sa.Text),
    _req("domain", sa.Text),
    _opt("origin_session_id", sa.Uuid),
    _req("status", sa.Text),
    _req("seen_count", sa.Integer),
    _opt("last_seen_session_id", sa.Uuid),
    _req("leech", sa.Boolean),
    _opt("provisional_expires_at", TS),
    _req("created_at", TS),
    _req("updated_at", TS),
)

review_states = sa.Table(
    "review_states",
    metadata,
    sa.Column("glossary_item_id", sa.Uuid, primary_key=True),
    _req("user_id", sa.Uuid),
    _opt("stability", sa.Double),
    _opt("difficulty", sa.Double),
    _req("due_at", TS),
    _opt("last_review_at", TS),
    _req("reps", sa.Integer),
    _req("lapses", sa.Integer),
    _req("last_ratings", ARRAY(sa.SmallInteger)),
)

review_logs = sa.Table(
    "review_logs",
    metadata,
    _uuid_pk(),
    _req("glossary_item_id", sa.Uuid),
    _req("user_id", sa.Uuid),
    _req("session_id", sa.Uuid),
    _req("rating", sa.SmallInteger),
    _req("reviewed_at", TS),
    _req("elapsed_days", sa.Double),
    _req("state_before", JSONB),
)

audit_log = sa.Table(
    "audit_log",
    metadata,
    _uuid_pk(),
    _opt("user_id", sa.Uuid),
    _req("event", sa.Text),
    _req("meta", JSONB),
    _req("at", TS),
)

web_sessions = sa.Table(
    "web_sessions",
    metadata,
    sa.Column("token_hash", sa.Text, primary_key=True),
    _opt("user_id", sa.Uuid),
    _req("csrf_token", sa.Text),
    _req("data", JSONB),
    _req("created_at", TS),
    _req("last_seen_at", TS),
)
